# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ale94mleon.github.io/
title: Alejandro Martínez León
email: ale94mleon@gmail.com
author: Alejandro Martínez León
description: "PhD student of Biophysics | MSCA"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/ale94mleon
  - icon: envelope-o
    title: email
    url: mailto:ale94mleon@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/alejandro-mart%C3%ADnez-le%C3%B3n-37abba198/
  - icon: file-pdf-o
    title: CV
    url: img/CV.pdf
  # - icon: twitter
  #   title: twitter
  #   url: https://twitter.com/jack-sparrow

